# Site
name:               Jalen (Jae-eun) Yang
title:              Graphics SW Engineer
bio:                'Graphics SW Engineer'
description:        ""
reading_time:       true
words_per_minute:   200
logo:               "Site/assets/profile/sydney_with_son.jpg"
background:         'Site/assets/img/placeholder-big.jpg'
icon:               'Site/assets/img/favicons/apple-icon-72x72.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://jaeeun.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   https-jaeeun-github-io

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:             "yangtkboy@gmail.com"
#twitter:           username
#facebook:          username
github-url:        "jaeeun"
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          "jaeeunyang"
#xing:              username
instagram:         "yangtkboy"
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
phone:              "+1-437-214-1185"
website:            "jaeeun.github.io"

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
